# Generated by Django 5.1.4 on 2024-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormTitle', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='forms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
