# Generated by Django 5.1.4 on 2025-01-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courseheader_alter_course_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.courseheader'),
            preserve_default=False,
        ),
    ]
