# Generated by Django 5.1.4 on 2025-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course_course_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
