# Generated by Django 5.1.4 on 2024-12-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdocument',
            old_name='FormTitle',
            new_name='title',
        ),
    ]
