# Generated by Django 5.1.4 on 2025-01-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_formtitle_formdocument_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='courseId',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='offered_by',
            new_name='offeredBy',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='offered_to',
            new_name='offeredTo',
        ),
    ]
