# Generated by Django 5.1.4 on 2025-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_course_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('faculty_mentors', models.CharField(max_length=255)),
                ('selected_students', models.TextField()),
            ],
        ),
    ]
