# Generated by Django 5.1.4 on 2025-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='faculty_mentors',
            field=models.TextField(),
        ),
    ]
