# Generated by Django 5.1.4 on 2025-01-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_project_faculty_mentors'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='equipment_product/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.equipmentsmodel')),
            ],
        ),
    ]
