# Generated by Django 5.1.4 on 2025-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_equipmentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='category',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Faculty Mentors', 'Faculty Mentors'), ('Lab Technician', 'Lab Technician')], default='Faculty Mentors', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentsmodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsmodel',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True),
        ),
    ]
