# Generated by Django 4.2.6 on 2025-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
