# Generated by Django 5.1.4 on 2025-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_faculty_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='category',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Faculty Mentors', 'Faculty Mentors'), ('Lab Technician', 'Lab Technician'), ('Administrators', 'Administrators')], default='Faculty Mentors', max_length=20),
        ),
    ]
